#this command executes another macro
#analysis.mac tells the program to store data for analysis
/control/execute analysis.mac

#set the file name
/analysis/setFileName output

#set the thickness of the lead reflector -- need a number and a unit
/testhadr/det/setReflectorThickness 2 cm

#initialize resets the geometry with the new reflector thickness
/run/initialize

#now produce neutrons
/run/beamOn 100000